// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221027201943_migration_destination_column")]
    partial class migration_destination_column
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.About", b =>
                {
                    b.Property<int>("aboutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("aboutDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aboutDescription2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aboutImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("aboutStatus")
                        .HasColumnType("bit");

                    b.Property<string>("aboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aboutTitle2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("aboutId");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.About2", b =>
                {
                    b.Property<int>("aboutId2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("aboutDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aboutImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aboutTitle2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("aboutId2");

                    b.ToTable("Abouts2");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Contact", b =>
                {
                    b.Property<int>("contactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("contactAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactMapLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("contactStatus")
                        .HasColumnType("bit");

                    b.HasKey("contactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Destination", b =>
                {
                    b.Property<int>("destinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("destinationCapacity")
                        .HasColumnType("int");

                    b.Property<string>("destinationCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destinationDayNight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destinationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destinationDetails1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destinationDetails2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destinationImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destinationImage2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("destinationPrice")
                        .HasColumnType("float");

                    b.Property<bool>("destinationStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("destinationcreateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("destinationId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Feature", b =>
                {
                    b.Property<int>("featureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("featurePostBigImage1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("featurePostDescription1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("featurePostImage1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("featurePostName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("featurePostStatus1")
                        .HasColumnType("bit");

                    b.HasKey("featureId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Feature2", b =>
                {
                    b.Property<int>("featureId2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("featurePostDescription2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("featurePostImage2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("featurePostName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("featurePostStatus2")
                        .HasColumnType("bit");

                    b.HasKey("featureId2");

                    b.ToTable("Features2");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Guide", b =>
                {
                    b.Property<int>("guideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("guideDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("guideImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("guideInstgram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("guideName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("guideStatus")
                        .HasColumnType("bit");

                    b.Property<string>("guideTwitter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("guideId");

                    b.ToTable("Guides");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Newsletter", b =>
                {
                    b.Property<int>("newsletterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("newsletterMail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("newsletterId");

                    b.ToTable("Newsletters");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SubAbout", b =>
                {
                    b.Property<int>("subAboutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("subAboutDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subAboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("subAboutId");

                    b.ToTable("SubAbouts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TestiMonial", b =>
                {
                    b.Property<int>("testiMonialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("testiMonialClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testiMonialClientImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testiMonialComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("testiMonialStatus")
                        .HasColumnType("bit");

                    b.HasKey("testiMonialId");

                    b.ToTable("TestiMonials");
                });
#pragma warning restore 612, 618
        }
    }
}
